# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innMateApp', '0002_auto_20160824_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='innMateApp.Guest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date_created',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date_updated',
            field=models.DateTimeField(verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
