# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innMateApp', '0003_auto_20160825_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='guest',
        ),
        migrations.AddField(
            model_name='visit',
            name='guestname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='innMateApp.Guest'),
        ),
    ]
